// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

using Wit.Native;
using Wit.Interop;

public static class ExportsInterop {
    private ExportsInterop() {}
    
    internal static unsafe void wasmExportFloat32Param(float p0) {
        Exports.Float32Param(p0);
        
    }
    internal static unsafe void wasmExportFloat64Param(double p0) {
        Exports.Float64Param(p0);
        
    }
    internal static unsafe float wasmExportFloat32Result() {
        return Exports.Float32Result();
        
    }
    internal static unsafe double wasmExportFloat64Result() {
        return Exports.Float64Result();
        
    }
    
}

