// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

using Wit.Native;
using Wit.Interop;

public static class Exports {
    private Exports() {}
    
    public static void Float32Param(float p0)
    {
        wasmExportFloat32Param(p0);
    }
    public static void Float64Param(double p0)
    {
        wasmExportFloat64Param(p0);
    }
    public static float Float32Result()
    {
        wasmExportFloat32Result();
    }
    public static double Float64Result()
    {
        wasmExportFloat64Result();
    }
    
}

