// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

using Wit.Native;
using Wit.Interop;

public static class Imports {
    private Imports() {}
    
    public static void float32Param(float x) {
        Float32ParamInterop.wasmImportFloat32Param(x);
        
    }
    public static void float64Param(double x) {
        Float64ParamInterop.wasmImportFloat64Param(x);
        
    }
    public static float float32Result() {
        var result =  Float32ResultInterop.wasmImportFloat32Result();
        return result;
        
    }
    public static double float64Result() {
        var result =  Float64ResultInterop.wasmImportFloat64Result();
        return result;
        
    }
    
}

