// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

using Wit.Native;
using Wit.Interop;

public static class ImportsInterop {
    private ImportsInterop() {}
    
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern unsafe void wasmImportFloat32Param(float p0);
    
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern unsafe void wasmImportFloat64Param(double p0);
    
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern unsafe float wasmImportFloat32Result();
    
    [MethodImpl(MethodImplOptions.InternalCall)]
    internal static extern unsafe double wasmImportFloat64Result();
    
}

