// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#ifndef __BINDINGS_THE_WORLD_H
#define __BINDINGS_THE_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Imported Functions from `foo:foo/floats`
void foo_foo_floats_float32_param(float x);
void foo_foo_floats_float64_param(double x);
float foo_foo_floats_float32_result(void);
double foo_foo_floats_float64_result(void);

// Exported Functions from `foo:foo/floats`
void exports_foo_foo_floats_float32_param(float x);
void exports_foo_foo_floats_float64_param(double x);
float exports_foo_foo_floats_float32_result(void);
double exports_foo_foo_floats_float64_result(void);

#ifdef __cplusplus
}
#endif
#endif
