// Generated by `wit-bindgen` 0.1.0. DO NOT EDIT!
namespace wit_the_world;

using System;
using System.Runtime.CompilerServices;
using System.Collections;

using Wit.Native;
using Wit.Interop;

public static class TheWorldWorld {
    private TheWorldWorld() {}
}
